/*
 * Keybad.c
 *
 *  Created on: Oct 9, 2024
 *      Author: Adam Aster
 */

#include "keypad.h"
#include "main.h"

void keypad()
 {
//Enabling Clock for Ports
	 RCC ->AHBENR|= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOBEN| RCC_AHBENR_GPIOCEN;
//Configuring Input Pins

	 //Specifying Pin Type: OUTPUT

	 GPIOA -> MODER |= (GPIO_MODER_MODER3_0|GPIO_MODER_MODER2_0|GPIO_MODER_MODER10_0);
	 GPIOA -> MODER &= ~ (GPIO_MODER_MODER3_1|GPIO_MODER_MODER2_1|GPIO_MODER_MODER10_1);
	 GPIOB -> MODER |= (GPIO_MODER_MODER3_0);
	 GPIOB -> MODER &= ~ (GPIO_MODER_MODER3_1);
	 GPIOC -> MODER |= (GPIO_MODER_MODER0_0| GPIO_MODER_MODER1_0|GPIO_MODER_MODER2_0|GPIO_MODER_MODER3_0);
	 GPIOC -> MODER &= ~(GPIO_MODER_MODER0_1| GPIO_MODER_MODER1_1|GPIO_MODER_MODER2_1|GPIO_MODER_MODER3_1);
	 //Specifying Pin Type: Push-Pull

	 GPIOA -> OTYPER &= ~( GPIO_OTYPER_OT_3 | GPIO_OTYPER_OT_2 | GPIO_OTYPER_OT_10);
	 GPIOB -> OTYPER &= ~( GPIO_OTYPER_OT_3);
	 GPIOC -> OTYPER &= ~(GPIO_OTYPER_OT_0|GPIO_OTYPER_OT_1|GPIO_OTYPER_OT_2|GPIO_OTYPER_OT_3 );
	 //Specifying Pin Speed

	 GPIOA-> OSPEEDR &=  ~(GPIO_OSPEEDR_OSPEEDR3_0 | GPIO_OSPEEDR_OSPEEDR2_0 | GPIO_OSPEEDR_OSPEEDR10_0);
	 GPIOB-> OSPEEDR &=  ~(GPIO_OSPEEDR_OSPEEDR3_0 );
	 GPIOC-> OSPEEDR &=  ~(GPIO_OSPEEDR_OSPEEDR0_0|  GPIO_OSPEEDR_OSPEEDR1_0|  GPIO_OSPEEDR_OSPEEDR2_0|  GPIO_OSPEEDR_OSPEEDR3_0);
	 //Specifying Pin: Pull Down

	 GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR3_0 | GPIO_PUPDR_PUPDR2_0 | GPIO_PUPDR_PUPDR10_0);
	 GPIOA->PUPDR |= (GPIO_PUPDR_PUPDR3_1 | GPIO_PUPDR_PUPDR2_1 | GPIO_PUPDR_PUPDR10_1);// Pull-down resistors
	 GPIOB->PUPDR &= ~GPIO_PUPDR_PUPDR3_0;
	 GPIOB ->PUPDR |= (GPIO_PUPDR_PUPDR3_1);
	 GPIOC ->PUPDR &= ~(GPIO_PUPDR_PUPDR0_0 |GPIO_PUPDR_PUPDR1_0 | GPIO_PUPDR_PUPDR2_0 | GPIO_PUPDR_PUPDR3_0);
	 GPIOC ->PUPDR |= (GPIO_PUPDR_PUPDR0_1 |GPIO_PUPDR_PUPDR1_1 | GPIO_PUPDR_PUPDR2_1 | GPIO_PUPDR_PUPDR3_1);
//Configuring INPUT Pins

	 //Specifying Pin Type: INPUT
	 GPIOB -> MODER &= ~(GPIO_MODER_MODER4|GPIO_MODER_MODER5|GPIO_MODER_MODER10);
	 GPIOA -> MODER &= ~(GPIO_MODER_MODER8);

	 //Specifying Pin Type: Push-Pull
	 GPIOA -> OTYPER &= ~( GPIO_OTYPER_OT_8);
	 GPIOB -> OTYPER &= ~( GPIO_OTYPER_OT_4 | GPIO_OTYPER_OT_5 | GPIO_OTYPER_OT_10);

	 //Specifying Pin Speed
	 GPIOA-> OSPEEDR &=  ~(GPIO_OSPEEDR_OSPEEDR8_0);
	 GPIOB-> OSPEEDR &=  ~(GPIO_OSPEEDR_OSPEEDR4_0 | GPIO_OSPEEDR_OSPEEDR5_0|  GPIO_OSPEEDR_OSPEEDR10_0);

	 //Specifying Pin: Pull Down
	 GPIOA->PUPDR &= ~(GPIO_PUPDR_PUPDR8_0);
	 GPIOA->PUPDR |= (GPIO_PUPDR_PUPDR8_1);// Pull-down resistors
	 GPIOB->PUPDR &= ~(GPIO_PUPDR_PUPDR4_0 |GPIO_PUPDR_PUPDR5_0|  GPIO_PUPDR_PUPDR10_0);
	 GPIOB ->PUPDR |= (GPIO_PUPDR_PUPDR4_1 | GPIO_PUPDR_PUPDR5_1|  GPIO_PUPDR_PUPDR10_1);

	 while(1){
		 // Set Row 1 (PA8) High, others Low
		 GPIOA->BSRR |= GPIO_BSRR_BR_3;    // Row 1 (PA8) High
		 GPIOA->BSRR |= GPIO_BSRR_BS_2 | GPIO_BSRR_BS_10; // Other rows Low
		 GPIOB->BSRR |= GPIO_BSRR_BS_3;

		         // Check if Column 1 (PB3) is high (key '1' pressed)
		 if(!(GPIOA -> ODR & GPIO_ODR_3)){
			 if (GPIOB->IDR & GPIO_IDR_5) { // If PB3 is high, key '1' is pressed
				 GPIOC->BSRR |= GPIO_BSRR_BS_0; // Turn on LED on PA9
			 } else {
				 GPIOC->BSRR |= GPIO_BSRR_BR_0; // Turn off LED on PA9
		         }

		         // Small delay for debouncing
		         delay(10);

		 }
	 }

	 }


